export class Constants {

    public static APPLICATIONS_MAPPING = {
        id: 'id',
        applicationTitle: 'application_title',
        applicantName: 'applicant_name',
        ceoName: 'ceo_name',
        ceoTitle: 'ceo_title',
        certifiedBy: 'certified_by',
        certifiedDt: 'certified_dt',
        certify1: 'certify_1',
        certify2: 'certify_2',
        completedOnTime: 'completed_on_time',
        completedOnTimeComments: 'completed_on_time_comments',
        hasNormalCosts: 'has_normal_costs',
        hasNormalCostsComments: 'has_normal_costs_comments',
        hasOtherFunding: 'has_other_funding',
        hasOtherFundingComments: 'has_other_funding_comments',
        isCovid: 'is_covid',
        isCovidComments: 'is_covid_comments',
        isNecessary: 'is_necessary',
        isNecessaryComments: 'is_necessary_comments',
        planAdminExpAmount: 'plan_admin_exp_amount',
        planAdminExpAmountTBC: 'plan_admin_exp_amount_tbc',
        planAdminExpDesc: 'plan_admin_exp_desc',
        planBudgetedDivertedAmount: 'plan_budgeted_diverted_amount',
        planBudgetedDivertedAmountTBC: 'plan_budgeted_diverted_amount_tbc',
        planBudgetedDivertedDesc: 'plan_budgeted_diverted_desc',
        planDistanceLearningAmount: 'plan_distance_learning_amount',
        planDistanceLearningAmountTBC: 'plan_distance_learning_amount_tbc',
        planDistanceLearningDesc: 'plan_distance_learning_desc',
        // planEconomicSupportAmount: 'plan_economic_support_amount',
        // planEconomicSupportAmountTBC: 'plan_economic_support_amount_tbc',
        // planEconomicSupportDesc: 'plan_economic_support_desc',
        planFoodAmount: 'plan_food_amount',
        planFoodAmountTBC: 'plan_food_amount_tbc',
        planFoodDesc: 'plan_food_desc',
        planHousingAmount: 'plan_housing_amount',
        planHousingAmountTBC: 'plan_housing_amount_tbc',
        planHousingDesc: 'plan_housing_desc',
        // planIssuanceOfTaxAmount: 'plan_issuance_of_tax_amount',
        // planIssuanceOfTaxAmountTBC: 'plan_issuance_of_tax_amount_tbc',
        // planIssuanceOfTaxDesc: 'plan_issuance_of_tax_desc',
        planMedicalAmount: 'plan_medical_amount',
        planMedicalAmountTBC: 'plan_medical_amount_tbc',
        planMedicalDesc: 'plan_medical_desc',
        // planNursingHomeAmount: 'plan_nursing_home_amount',
        // planNursingHomeAmountTBC: 'plan_nursing_home_amount_tbc',
        // planNursingHomeDesc: 'plan_nursing_home_desc',
        planOtherItemsAmount: 'plan_other_items_amount',
        planOtherItemsAmountTBC: 'plan_other_items_amount_tbc',
        planOtherItemsDesc: 'plan_other_items_desc',
        planPayrollAmount: 'plan_payroll_amount',
        planPayrollAmountTBC: 'plan_payroll_amount_tbc',
        planPayrollDesc: 'plan_payroll_desc',
        planPpeAmount: 'plan_ppe_amount',
        planPpeAmountTBC: 'plan_ppe_amount_tbc',
        planPpeDesc: 'plan_ppe_desc',
        planPublicHealthAmount: 'plan_public_health_amount',
        planPublicHealthAmountTBC: 'plan_public_health_amount_tbc',
        planPublicHealthDesc: 'plan_public_health_desc',
        // planSmallBusinessAmount: 'plan_small_business_amount',
        // planSmallBusinessAmountTBC: 'plan_small_business_amount_tbc',
        // planSmallBusinessDesc: 'plan_small_business_desc',
        planTeleworkAmount: 'plan_telework_amount',
        planTeleworkAmountTBC: 'plan_telework_amount_tbc',
        planTeleworkDesc: 'plan_telework_desc',
        // planTestingAmount: 'plan_testing_amount',
        // planTestingAmountTBC: 'plan_testing_amount_tbc',
        // planTestingDesc: 'plan_testing_desc',
        // planUnemploymentAmount: 'plan_unemployment_amount',
        // planUnemploymentAmountTBC: 'plan_unemployment_amount_tbc',
        // planUnemploymentDesc: 'plan_unemployment_desc',
        // planWorkersCompAmount: 'plan_workers_comp_amount',
        // planWorkersCompAmountTBC: 'plan_workers_comp_amount_tbc',
        // planWorkersCompDesc: 'plan_workers_comp_desc',
        projectDefinition: 'project_definition',
        projectDescription: 'project_description',
        relatedApplicants: 'related_applicants',
        workCompletedTotal: 'work_completed_total',
        workToBeCompletedTotal: 'work_to_be_completed_total',
        status: 'status',
        dateOfApplicantSubmission: 'date_of_applicant_submission'
    };

    public static APPLICATIONS_MAPPING_REQUIRED: Array<string> = [
        'certify1',
        'certify2'
    ];

}

